### ISSUE TITLE
Dot Shield blank on Dot Browser New Tab Page

### ISSUE THREAD

**Issue by ejaz4** [dothq-extensions/adblock#42]
**Describe the bug**
Dot Shield UI is mostly blank on the Dot Browser NTP (aka Firefox NTP).

**To Reproduce**

1. Launch Dot Browser
2. Go to about:newtab or open a new tab.
3. Click on Dot Shield

**Expected behavior**
Dot Shield UI would be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/73548455/114231165-f8d51380-9971-11eb-9506-1ed81aa8fd04.png)
![image](https://user-images.githubusercontent.com/73548455/114231649-9cbebf00-9972-11eb-844e-ff143350f75b.png)

**Desktop (please complete the following information):**

- OS: Windows NT 10.0
- Browser: Dot Browser 87.0
- Version: 0.1.0pre6

**Additional context**
I have only tested this with the version of Dot Shield bundled with Dot Browser.

**Comment by EnderDev** [comment]
This is occuring because the adblocker doesn't have permission to that site. No extension has access to about:* pages afaik.

**Comment by ejaz4** [comment]
> 
> 
> This is occurring because the adblocker doesn't have permission to that site. No extension has access to about:* pages afaik.

Weird, as it works on other about:* pages such as about:preferences and about:config
![image](https://user-images.githubusercontent.com/73548455/114241928-e82c9980-9981-11eb-9818-c25a6a3df3be.png)

**Comment by EnderDev** [comment]
It shouldn't work on any about:* pages, maybe we should just hide the adblocker icon when you're on a page that it has no permission to

**Comment by trickypr** [comment]
Fun, my contrast code has broken itself. I’ll fix it tonight

**Comment by trickypr** [comment]
This is now patched on main

**Comment by trickypr** [comment]
> This is occurring because the adblocker doesn't have permission to that site. No extension has access to about:* pages afaik.
Incorrect, it occurred because my contrast code was being broken for some reason, something to do with not taking into account rgb(a) values and whitelisted color changes.
